### ISSUE TITLE
borgbase_ssh always marked as changed

### ISSUE THREAD

**Issue by sinux-l5d** [adhawkins/ansible-borgbase#12]
Hi,

Every time I run my playbook using borgbase_ssh, the task is always marked as changed when state=present.

The relevant code seems to be: https://github.com/adhawkins/ansible-borgbase/blob/544ff2f002cd952aa8b689434f20523f06fea8b4/plugins/modules/borgbase_ssh.py#L239

The borgbase api returns the key formatted as "_algorithm data_", but the ssh key file is formatted as "_algorithm data keyname_".

Except if you think it's up to the user to provide a well-formatted key, the easiest solution I find (but maybe dirty?) would be to replace the if statement with those couple lines: 
```py
 # only keep algorithm and data, the first two fields separated by whitespaces
providedKey = " ".join(module.params['key'].strip().split()[:2])
if providedKey != foundKey['keyData']: 
```

If you think it's okay, I can submit a pull request

**Comment by adhawkins** [comment]
That's odd. I use borgbase_ssh in my playbooks, and have never had an issue with this.

Let me do some checks to see if I can recreate it.

**Comment by sinux-l5d** [comment]
I have to mention that the SSH key is automatically generated for root by borgbase_ssh, I didn't previously created it. The keyname/comment by default is "ansible-generated on <hostname>"

**Comment by adhawkins** [comment]
Just checked, and some of my .pub files include the 3rd section, and some don't. Will have a play to double check, because I must have used one of the ones that does include that information.

**Comment by sinux-l5d** [comment]
In the meantime, a workaround is : `key: "{{ (ssh_key.content | b64decode).split()[:2] | join(' ') }}"`, at list in my case

**Comment by adhawkins** [comment]
Ok, confirmed that I see the same issue here. Are you able to test your proposed fix in the module itself? If so, please do so then go ahead and create a Pull Request. Appreciate you finding this!

**Comment by adhawkins** [comment]
I'm about to release a new version of the plugins as a result of some other changes at Borgbase. Are you able to submit a pull request for this change so that you can get appropriate credit?

**Comment by sinux-l5d** [comment]
Thanks for reminding me, I'm having a look right now

**Comment by sinux-l5d** [comment]
Apparently, I seems to have found a workaround, because I can't reproduce the issue anymore.

I'm using `adhawkins-borgbase` version `1.0.0`.

Here is a sample of my playbook:

```yaml
- name: Generate SSH key for Borg
  community.crypto.openssh_keypair:
    path: "/root/.ssh/borg"
    state: present
    type: ed25519
    force: no
    owner: root
  register: ssh_key
  
- name: Upload public key in Borgbase
  adhawkins.borgbase.borgbase_ssh:
    state: present
    apikey: "{{ borgbase_apikey }}"
    name: "ANSIBLE-1"
    key: "{{ ssh_key.public_key }}" 
  register: borgbase_key
 ```

I will create a PR with the initial fix I proposed, as it might still be a problem for user not using `community.crypto.openssh_keypair` I guess
