### ISSUE TITLE
Using the repo module always errors out with 'Nonetype' object is not iterable

### ISSUE THREAD

**Issue by Nabsku** [adhawkins/ansible-borgbase#18]
Running 
```    
 - name: Ensure  that repo has append_only key set
    adhawkins.borgbase.borgbase_repo:
        apikey: "{{ BORGBASE_API_KEY }}"
        name: "{{ inventory_hostname }}"
        region: "{{ borgbase_repo_region }}"
        append_only_keys: [ "{{ borgbase_key.key_id }}" ]
        append_only: "{{ append_only_repo }}"
     register: borgbase_repo
```
returns 

 ```worker1 | FAILED | 1.35s
{
  - msg: 'NoneType' object is not iterable
  - changed: True
} 
```
no matter what I do. Creating a repo using python and the graphql api works flawlessly, using the same variables as used above. Any idea why this isn't working? Variables are all defined.

**Comment by adhawkins** [comment]
Are you using the latest version, released recently?

Can you please provide the exact values for the variables you're passing in (with the exception of authentication information obviously).

**Comment by Nabsku** [comment]
Using the latest version, yes.

```
collections:
  - name: adhawkins.borgbase
    version: 1.0.2
```

Values of variables are as follows: 

``` 
borgbase_repo_region: eu
append_only_repo: true
inventory_hostname: pi1 (for example, happens to every host)
```

key_id is derived from: 

```
 - name: Add SSH key on Borgbase
    adhawkins.borgbase.borgbase_ssh:
      apikey: "{{ BORGBASE_API_KEY }}"
      name: "{{ inventory_hostname }}"
      key: "{{ ssh_key['content'] | b64decode }}"
      state: present
    register: borgbase_key
```
where ssh_key is derived from: 
```
- name: Gather SSH pub key
   ansible.builtin.slurp:
      src: ~/.ssh/id_ed25519.pub
    register: ssh_key
```
Weirdly enough, adding/removing SSH keys works flawlessly..
